name: 'Tag latest'
description: 'Tag the latest successful commit with the "latest" tag'
author: 'CallRail'
inputs:
  github_token: # change this
    required: true
    description: 'GH token'
    default: ''
  latest_tag_name:
    required: false
    description: 'Tag name to find/delete/create'
    default: 'latest'
runs:
  using: 'node12'
  main: 'dist/index.js'
