name: 'Tag latest'
description: 'Tag the latest successful commit with the "latest" tag'
author: 'CallRail'
inputs:
  github_token: # change this
    required: true
    description: 'GH token'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
