name: 'build-test'
on: # rebuild any PRs and main branch changes
  status:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  tag_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./dist
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          latest_tag_name: 'stable'
